# Introduction

```{r parte_1, include=FALSE}
#### Code I: Itroducction ####
```

Reproductive processes strongly influence the distribution and abundance patterns of benthic species. These aspects are influenced mainly by local coastal dynamics, which can transport or retain larvae near spawning areas, modify the duration of larval development through changes in water temperature (O’Connor et al., 2007), and affect the distribution of adults (Bhaud, 1993; Giangrande et al., 1994; Grantham et al., 2003; Ospina-Alvarez et al., 2020). Moreover, the recruitment of benthic species depends on reproductive success, larval abundance and dispersal, settlement success, and post-settlement survival under environmental conditions that may be subject to anthropogenic effects (Hunt and Scheibling, 1997; Ouréns et al., 2014). All of these factors interact at different scales, inducing high levels of spatial and temporal variability in recruitment (Pineda, 2000; Botsford, 2001; Pineda et al., 2009). At a regional scale (i.e., 10-1000 km), changes in geomorphology and coastal oceanographic regimes affect the advective loss of larvae from settlement areas and, consequently, the recruitment success of many species (Morgan et al., 2000; Lagos et al., 2008; Ebert, 2010). At smaller scales (0.1-10 km), local factors can strongly affect nearshore larval distributions (Tapia and Pineda, 2007; Shanks and Shearman, 2009), patterns of settlement (Pineda, 1994; Ladah et al., 2005), or early mortality of benthic individuals (Hunt and Scheibling, 1997).

In Chile, one of the most important and commercially exploited benthic species is the surf clam _Mesodesma donacium_. This species inhabits sandy beaches along the Chilean coast, from Arica to southern Chiloé (18-43ºS). It forms dense aggregations that are associated with morpho-dynamic beach features such as grain-size distribution, steepness, and profile (Jaramillo et al., 1994). The landing records for _M. donacium_ reveal boom and bust cycles, with significant spatial and temporal fluctuations in landings, which have been described as serial depletion in the populations distributed along the Chilean coast (Thiel et al., 2007). Initially, in the 1960s and 1970s, harvesting for this species was concentrated mainly in the northern region (Matamala et al., 2008), particularly in the sandy banks of Coquimbo. During the late 1980s, banks in the southern zone near Mehuin were under significant extraction pressure. The fishery practically disappeared in the mid-1990s and started again in 1998 with the simultaneous harvesting of 10 banks in the southern Los Lagos Region (Rubilar et al., 2001; Stotz et al., 2003). The high variability observed in the harvesting of surf clam has been attributed to ENSO effects on their survival and reproductive biology (Arntz et al., 1987; Riascos et al., 2009; Carstensen et al., 2010; Ibarcena Fernández et al., 2019). Nevertheless, recruitment variability could be caused by density-dependent effects (Lima et al., 2000), and is probably associated with adult life span (Ripley and Caswell, 2006).

In recent years, the fishery for the surf clam _M. donacium_ has focused on three main sections of the Chilean coast: a) Coquimbo Region (29-30ºS), with high inter-annual variability in landings, which are concentrated at two main coves (Los Choros and Peñuelas, Fig. 1); b) “Caleta Quidico” in the Biobío Region (38ºS), where most of the national landings were concentrated between 2001 and 2004, with a rapid depletion of the bank after that; and, c) Los Lagos Region (42-43ºS), with three main coves (Maullín, Mar Brava, and Cucao) accounting for landings that increased substantially in 2009-2011, and then dropped to reach a minimum in 2016 (Fig. 1).

In Chile, benthic fisheries are managed through an administrative system known as “Areas for the Management and Exploitation of Benthic Resources” (AMEBR) which is based on a Territorial User Rights for Fisheries (TURF) system, in which a geographical coastal area is allocated to artisanal-fisher organizations through temporary rights to harvest benthic species. Fishers must provide baseline information and a managing plan for target benthic species, derived from field surveys, which are often conducted by private consultants. Based on these surveys, the management agency (Undersecretariat of Fisheries and Aquaculture, SUBPESCA) authorizes to harvest a given quota for the target species, seeking to safeguard the ecosystem’s natural recovery (González et al., 2006; Gelcich et al., 2010; Marín and Gelcich, 2012; Aburto et al., 2013).

In the AMEBR system, the management procedure (MP) consists of a) an annual assessment of the standing stock, which provides estimates of biomass and length-composition; b) estimation of a target fishing mortality, usually the F0.1 (Deriso, 1987) by assuming a pseudo-cohort and applying the yield-per-recruit model of Thompson and Bell (e.g., Doubleday and Esunge, 2011; Mildenberger et al., 2017); and c) estimation of a total allowable catch (TAC), which must be authorized to be harvested by SUBPESCA. This MP repeats annually without taking into account past surveys and removals and would be inadequate to ensure the sustainable exploitation of benthic species with non-annual recruitment, such as the surf clam _M. donacium_.

Unfortunately, one crucial weakness of the surf clam fishery in Chile is the incomplete recording of landings at coves and landing ports. Additionally, there is a lack of management plans that simultaneously consider the impact of users and environmental variability on the target species’ availability, which increases the cost of maintaining monitoring programs (CCT-B, 2014). Often, these fisheries are data-poor, which makes it challenging to apply quantitative methods of population assessment, such as integrated statistical catch-at-length (age) analysis (Smith et al., 2009; Punt et al., 2011). Thus, the local depletion of surf clam populations observed along the Chilean coast over the past decades has not been adequately evaluated yet due to a lack of data, which has hampered attempts to test whether local depletion was due to fishing effects or larger-scale, oceanographically driven changes in population dynamics.

At Cucao beach in northern Patagonia, data from direct stock assessments of surf clam are available annually for the seven years 2011-2017. During this period, different consultants conducted surveys and produced estimates of abundance and annual quotas under the assumption that this species recruits annually. Decisions on harvest limits for this area were taken considering those annual quota estimates. In this study, we use the 7-year data set from stock assessment surveys to implement an operating model for the population dynamics of Mesodesma donacium at Cucao beach. The implemented model allows for inter-annual variability in recruitment to be simulated, to assess the management procedure currently applied to AMEBRs, and to provide estimates of harvest rates that could achieve sustainable exploitation given the high temporal variability in recruitment detected for this fishery in the recent past.
