# Materials and methods

```{r parte_2, include=FALSE}
#### Code II: Materials and methods ####
```

## Study area and data sources

The study area is Cucao beach (24º36’S-74º08’W), located on the western shore of Chiloé island, northern Chilean Patagonia (Fig. 1). Over the past decade, Cucao has been one of the main harvesting areas for the surf clam _M. donacium_, with three organizations of artisanal fishers having territorial use rights since 2015 (Fig. 1). The data were obtained from six stock assessment surveys carried out between 2011 and 2017 (Table 1). Before 2015, the stock assessments of surf clam were carried out to establish annual catch quotas [@Leal2014]. Since 2015, data from the assessments became input information for harvesting surf clam under the AMEBR management procedure.

## Evaluation of the management procedure

A simulation was implemented to evaluate the performance of the management procedure (MP) for _M. donacium_ in Cucao. The simulation involved the steps of the Management Strategy Evaluation (MSE) framework [@Starr1997; @Cochrane1998; @Punt2016; @Kell2017]. In this framework, one of the steps is conditioning an Operating Model (OM) based on data and knowledge for the surf clam population dynamics. The OM allowed us to evaluate the MP under uncertainty (Fig. 2), especially in terms of recruitment, which during the studied period exhibited pulses of high recruitment followed by years of low to nil recruitment. The OM allowed simulating the perceived vulnerable biomass in the stock assessment surveys for a window of 20 years into the future, along with the quota and the realized total harvest under a constant harvest rate strategy.

The simulation modeling to evaluate the MP for surf clam consisted of the steps described in the following sections: Section A describes the current MP for surf clam in Cucao. Section B describes the OM that specifies the true structure and processes modulating the surf clam population dynamics, with emphasis on conditioning the OM to the available data and knowledge [@Kell2017]. Section C describes the phase of projecting the operating model 20 years into the future. For each year, the OM provides a population that can be sampled in a way similar to the stock assessment surveys carried out in the field. The projected OM included the recruitment dynamics and its response to fishing and environmental forcing. Section D describes the statistics used to summarize the performance of the current and alternative management procedures for surf clam in Cucao.

## Section A: The management procedure for surf clam

The management procedure corresponding to the Cucao AMEBR is shown in Figure 3. A team of technicians and professional divers carry out a stock assessment survey annually (see Table 1). The survey is designed to provide estimates of total abundance and biomass in the surveyed area. The estimate of biomass is size-structured, allowing the estimation of vulnerable biomass, which is defined by surf clams larger than 50 mm length (i.e., the minimum legal size). The stock assessment team computes yield per recruit using a Thomson and Bell model, and then $F_{0.1}$ [@Deriso1987] to compute the quota to be harvested. Nevertheless, in practical terms, the harvest decision has resulted in a constant Quota/Vulnerable biomass ratio of approximately 25% (Table 1). Thus, the current management procedure can be simplified by formulating the following empirical harvest control rule:

1) $Q_i=0.25 V_i$

where $V_i$ is the survey estimate for vulnerable biomass in the i-th year and $Q_i$ is the quota of surf clam requested by the fishers organizations to the centralized management agency, i.e., the Undersecretariat of Fisheries and Aquaculture (SUBPESCA), which reviews the technical reports and approves the harvest quotas. The management procedure is essentially empirical since it uses the vulnerable biomass estimated in the survey as an indicator of the surf clam status, and the primary input to the harvest control rule (Table 1). Once SUBPESCA approves the quota, fishers can harvest the surf clam from the management area. At the time of harvest, catches are monitored and logged by the Chilean National Fisheries Service (SERNAPESCA).

## Section B: The operating model

The operating model (OM) was conditioned to know life-history parameters of surf clam and total biomass and population size-structure data obtained from the direct stock-assessment surveys (Table 1 and Table 2). The OM was based on an integrative size-structured stock assessment model [@Sullivan1990; @Punt2013], expressed by

2) $N_{i,l}=G_{l,l'} N_{i-1,l} e^{-Z_{i-1,l} }+ r_l R_i$

where $N_{i,l}$ is the abundance of length-class $l$ at the beginning of year $i$, $Z$ is the instantaneous total mortality rate, i.e., $Z=F+M$, where $F$ is the fishing mortality, and M is the natural mortality rate (set equal to 0.3). $R_i$ is recruitment, $r_l$ is the distribution of recruitment by length-classes, and $G_{l,l'}$ is a growth transition matrix described by

3) $G_{l,l'}=\int_l^{l'} (l'-l)^{\alpha_j}  e^{-(l'-l)/\beta_p } dl/\beta_p$

where $l$ is the length class, and $\alpha_j$ and $\beta_p$ are parameters describing a gamma probability function. Recruitment was estimated according to:

4) $R_i = \bar{R}e^{\epsilon_i}$

where $\bar{R}$ is the average recruitment and $\epsilon_i$ is the annual deviation, which followed a normal distribution $N(0,\sigma_R)$.

The recruitment probability at length was assumed to be normal, i.e.,

5) $r_l=\int_l^{l+1}\frac{1}{\sqrt{2\pi\sigma^2}} e^{(-(l-l_r)^2/2\sigma^2)}dl$

where $l_r$ is the mean length at recruitment and $\sigma^2$ is the variance of length at recruitment.

The fishing mortality rate during the year $i$ and length $l$ $(F_{i,l})$ was computed by

6) $F_{i,l} = F_i s_l$

where $F_i$ is the annual fishing mortality rate, and $s_l$ is the selectivity at length $l$, which was defined by

7) $s_l =0 \text{   if   } l < 50 \text{;  or   } s_l = 1 \text{     if      } l \geqslant 50$

The selectivity in Eq. 7 is a ‘knife-edge’ function of minimum legal size ($l_c=50$) mm.

The model for observations consisted of the total annual harvest and total biomass in the surveys. Catch by number was estimated according to the Baranov catch equation, i.e.,

8) $C_{i,l}=F_{i,l} N_l (1-e^{-Z_{i,l}})/Z_{i,l}$

where $C_{i,l}$ is the catch in the year $i$ at length class $l$. The total annual harvest ($Y_i$) was estimated by:

9) $Y_i=\sum_l W_l C_{i,l}$

where $W_l$ is the average weight at length class $l$.

Length composition in the population was estimated by:

10) $p_{i,l}=N_{i,l}/(\sum_l N_{i,l})$

The population biomass at the time of the survey (within the year) was computed by:

11) $B_i=\psi \sum_l v_l W_l N_{i,l} e^{-\tau Z_{i,l}}$

where $\psi$ is the catchability coefficient and assumed to be equal to 0.99, $v_l$ is the selectivity at length of the survey and assumed to be constant and equal to 1 for all length classes, and $\tau$ is the time of year in which the stock assessment survey was carried out (Table 1). After that, the vulnerable biomass in the direct stock assessment surveys ($V_i$) was simulated according to:

12) $V_i = \psi \sum_l v_l W_l N_{i,l} e^{-\tau Z_{i,l}}$

Total biomass was computed as the sum of products between the abundance and the average weight at length, and the spawning biomass was computed by:

13) $S_i=\sum_l m_l W_l N_l e^{-T_s Z_{i,l}}$

where $m_l$ is the female maturity ogive, $T_s$ is the beginning of the spawning time within a year (set at 0.81). The model was conditioned to the available data and known surf clam life-history parameters and consisted of estimating the unknown parameters by fitting the population dynamics to the data (Table 1 and 2). The objective function consisted of negative log-likelihood functions and penalized priors (Table 2 and Table 3). The model was conditioned through an estimation procedure implemented in ADMB [@Fournier2012].

## Section C: Simulation of the management procedure

Once the OM was conditioned to the data and known life history parameters, a forward projection phase of the population dynamics allowed simulating the management procedure over 20 years. The recruitment dynamics followed a Beverton and Holt stock-recruitment relationship (SRR), described by:

14) $R_i=\frac{4 h R_0 S_{i-1}}{(1-h) S_0+(5h-1) S_{i-1}} e^{\epsilon_i - 0.5\sigma_R^2}$	

where $R_0$ is the average unexploited recruitment, assumed to be equal to the average recruitment in the period 2011-2017 (i.e., $R_0=\bar{R}$), $S_0$ is the average unexploited spawning biomass that produces $R_0$, and $h$ is the steepness [@Francis1992; @Dorn2002; @Lee2012], which was set equal to 0.7 considering estimates for the surf clam _Spisula solidissima_ [@Powell2015; @Hennen2018]. In Eq. 14, recruitment is a function of both the spawning biomass and the environmental forcing, which is considered in the simulation by allowing $\epsilon_i$ to vary as a sequence of switches in the operating model, i.e.

15) $\epsilon_i=E_i e^{(\delta_i)}$

where $E_i$ is the environmental forcing represented as a sequence of switches that are alternating between two-year periods in which recruitment is favored ($E_i = 1$) followed by two-year periods in which recruitment is not favored ($E_i = -1$). The sequence of switches was perturbed by stochastic annual deviations ($\delta i$) following a normal distribution, i.e., $N(0,\sigma_R)$. Equation 15 allowed the simulation of future recruitment as a pattern similar to the changes observed in the recruitment estimates obtained from the stock assessments of 2011-2017.

The management procedure considered the current harvest rate of 25%, but for comparison purposes, alternative values of 0, 10, 15, 20, and 30% were also considered. The exploitation rate $\mu=0$ was implemented to simulate the unexploited surf clam population as a reference. The simulation was performed under uncertainty, sampling from the posterior of the fitted model through Markov Chain Monte Carlo (MCMC). The number of MCMC was obtained from 10,000 samples and saving every 200 by using the metropolis algorithm implemented in ADMB [@Fournier2012].

## Section D: Performance evaluation

The trajectory of simulated recruitment, spawning biomass, and fishing mortality resulting from the MP was summarized with confidence intervals of 90% by applying a percentile method to all realizations obtained by MCMC. Depletion was computed as the ratio between the spawning biomass in a given year and the average unexploited spawning biomass. Also, a reduction of 40% in the spawning biomass from the average unexploited value was considered as a target reference point, i.e., $S_{\text{target}} = 0.4S_0$. Therefore, exploitation rates generating reductions below the target were considered unsustainable for the surf clam population. The probability of keeping the target was computed as $Pr[S_i⁄S_{\text{target}} > 1]$, whereas the probability of a collapse was computed as $Pr[S_i⁄S_{\text{target}} \leq 0.5]$. Exploitation rates generating probabilities of achieving the target above 0.5 were used as a reference for good performance.
