# Discussion

```{r parte_4, include=FALSE}
#### Code IV: Discussion ####
```

Recruitment of benthic marine invertebrates is a highly complex process that spans a range of spatio-temporal scales (Defeo, 1996; Pineda and Caswell, 1997) and that is modulated by environmental forcing (e.g., winds, waves, physiological stress) that limits larval survival and successful settlement (Pineda, 1991; Cushing, 1995). Additionally, density-dependent factors operating at different spatial scales are prevalent in marine invertebrates (Hixon et al., 2012), leading to reduced reproductive success and survival of adults (Stephens, 1999). Adult density can positively or negatively affect recruitment success, which then determines adult density patterns (Jenkins et al., 2009). Both factors (i.e., environment and density-dependence) are not mutually exclusive, but interact to determine the densities of marine benthic populations and assemblages.

The recruitment estimates for the surf clam _M. donacium_ in the period 2011-2017, and that conditioned the operating model (OM), showed the alternation of periods with high and low recruitment in the Cucao beach population, despite the short data series available. Two years with high recruitment were followed by poor recruitment in 2016, after a warm ENSO event in 2015-2016 (Jacox et al., 2016; Martínez et al., 2017). 

Recruitment failures and high temporal variability are common features in the population dynamics of surf clams (Lima et al., 2000; Ripley and Caswell, 2006; Aburto et al., 2013). These are general features in the population dynamics of many species with short life cycles and can be linked to high rates of natural mortality and greater variability in growth rates (Bjørkvoll et al., 2012). These generalizations notwithstanding, the estimated lifespan of the surf clam _M. donacium_ at Cucao was close to 7 years, with cohorts showing a modal progression in the size structure from 2011 to 2017. The estimated von Bertalanffy growth parameter ($K=0.21$ year$^{-1}$) indicates theoretical longevity close to 15 years, i.e., $t_{max} \sim 3/K$ (Kenchington, 2014). Thus, the population’s age-structure may act as a filter of recruitment variability, dampening the effects of environmental variability on population renewal, and hence reducing the influence of the environment on the stock (Planque et al., 2010).

Recruitment in _M. donacium_ is hard to miss during the stock assessment surveys since post-settled individuals are easily distinguishable in the field and tend to accumulate in the swash zone and near the mouth of estuaries or small rivers (Jaramillo et al., 1994). Thus, as has been demonstrated in this study, the recruitment of surf clams at Cucao beach does not always contribute noticeably to the exploited stock biomass. Thus, settlement numbers or post-settlement mortality, or both, may vary widely from year to year, which suggests that environmental phenomena connected with the dispersal of larvae or the physiology of post-settled individuals may condition the stock’s renewal. Although the information collected to date limits the inferences that can be made about environmental phenomena that may limit recruitment success in the surf clam _M. donacium_, it is likely that a specific combination of wave and wind conditions, at the right time of year, is required for competent larvae to reach the shore and settle. The total number of competent larvae that could reach the shore, in turn, is likely to depend on advective and feeding conditions in shelf waters during the weeks or months before the recruitment period.

It has been documented that environmental variability affects the abundance of _M. donacium_ further north. For example, during the 1997-1998 El Niño, the collapse of the surf clam populations in Arica (18º30’S) and Huasco (28º30’S) was attributed to this phenomenon, in connection with coastal flooding and excess rainfall (Jerez et al., 1999). In Peru, high mortality of adult _M. donacium_ was attributed to the increase in temperatures caused by the 1982-1983 El Niño (Arntz et al., 1987, 1988). Infrequent recruitment of surf clams has also been reported previously in northern Chile, possibly in association with environmental factors that affect the release of gametes as well as oceanographic factors affecting the survival and onshore supply of planktonic larvae (Thiel et al., 2007). It is common to hear artisanal fishers talk about a “green” surf clam with lengths of $3-4$ cm that is occasionally found in the exploited banks. This is consistent with the occasional appearance of juveniles in the annual surveys at Cucao beach, where small individuals (lengths $2.5-5.0$ cm) appeared in large numbers in only one out of seven stock-assessment surveys (2016). The inconsistent occurrence of juveniles observed in the stock-assessment surveys was not an artifact of survey mistiming (relative to recruitment), as indicated by the inter-annual consistency and progression of gaps in the size-structure data collected during surveys.

For fisheries management, the observed recruitment failures imply that, if recruitment occurs approximately once every three years, the exploitation rates should be lower than those recommended by the current management procedure ($\mu= 25$%), and that lower exploitation rates ($µ \leq 15$%) are needed to ensure sustainable exploitation in the medium term. Furthermore, the current lack of knowledge on the spatial-temporal variability of settlement and recruitment in species such as the surf clam _M. donacium_ puts into question the exploitation strategies that are currently considered as sustainable. Typically, it is assumed that benthic species have annual recruitment, which is not the case for _M. donacium_. Therefore, this contribution highlights an issue that warrants an even more precautionary approach to the commercial exploitation of benthic species with non-annual, or irregular recruitment.

A management procedure can be viewed as a “static” or memory-lacking process since it does not refer to either past or future observations. Indeed, annual quotas are computed from the standing stock assessed directly in the field. The size-structure data are converted into age composition data through the slicing age-class method, which is the primary input for the yield-per-recruit model of Thompson and Bell. This model assumes that age-classes are treated as a “pseudo-cohorts” without considering past recruitment to explain the current length- or age-composition. Also, the estimation of $F_{0.1}$ has an implicit economic objective because it is computed from the yield-per-recruit curve, but $F_{0.1}$ is implicitly a function of age at first catch and, hence, knife-edge selectivity (Deriso, 1987; Quinn and Deriso, 1999), which is probably adequate for the surf clam population. 

Nevertheless, although $F_{0.1}$ is more conservative than $F_{max}$, it is questionable considering the spawning potential ratio (Shepherd, 1982; Sissenwine and Shepherd, 1987). Indeed, the realized harvest rate associated to $F_{0.1}$ was close to 25% in the management procedure and resulted in being excessive according to the surf clam population dynamics here used as an operating model. It is advisable to apply a harvest rate of 15%, which may be enough to keep the reproductive potential of the surf clam population. Furthermore, it is advisable to implement a harvest control rule in which the harvest rate declines when the spawning stock declines due to lower recruitment. The ramp-like harvest control rule could be more effective for a rapid recovery of the spawning biomass, dampening the probability of unobserved or lower recruitments in the future. Reducing exploitation as the stock declines results in added resilience against environmental variability and, eventually, climate change (e.g., Merino et al., 2017).

In general, the above described “static” or “memory-lacking” procedure management is applied to almost all of the management areas (AMEBR) in Chile, as documented in the management and exploitation plan for each target species (Gallardo et al., 2011). Our analyses revealed that surf clam recruitment does not occur annually, or even periodically, with a separation of 3 or more years between high recruitment episodes. The landing records from other areas where surf clam populations were depleted in previous decades show that exploitation could be unsustainable when the harvest rate intensity is not controlled. This behavior is typical in the exploitation of surf clam _M. donacium_ along the Chilean coast (e.g., Aburto and Stotz, 2013), as well as for other surf clam species (Weinberg, 1999; Laudien et al., 2003; Fiori and Morsán, 2004; Ripley and Caswell, 2006; Herrmann et al., 2011).

The underlying problem is that, in practice, little is known about the intensity and success of recruitment in harvested marine populations, which can be attributed to biases introduced by the extractive activity itself (e.g., Punt and Cope, 2019). Sampling from the commercial catch is usually carried out on landings, which leaves out juvenile fractions. In the case of benthic species harvested from AMEBRs (Chile), population surveys usually consider the fraction that can be detected visually by scientific divers. Although this procedure includes individuals under commercial size, it is likely to leave out newly settled individuals, which are not always visible due to small size, pigmentation, or behavior. Thus, the quantification of newly established fractions in populations of commercial species usually is fraught with uncertainty and should be approached through indirect methods. For management areas where biomass and length-composition have been recorded annually over a long-enough period, it is advisable to implement an integrated stock-assessment model (Smith et al., 2009; Punt et al., 2011). Subsequently, biological reference points should be established as a means to assess the population’s status, and to set a TAC based on population projections. Thereafter, the AMEBR’s management procedure must be changed to keep the exploitation of benthic species within biologically safe margins.
